### ISSUE TITLE
upgrading electron in source trows error

### ISSUE THREAD

**Issue by jarno9981** [Sential/wexond#619]
when trying update electron with the nightly error comes

**Comment by jarno9981** [comment]
A JavaScript error orcured in main process

console Info:


$ cross-env START=1 npm run watch

> wexond@6.0.0-nightly.2 watch
> concurrently "npm run dev-renderer" "npm run dev-webpack"

[0] 
[0] > wexond@6.0.0-nightly.2 dev-renderer
[0] > cross-env DEV=1 webpack serve --config webpack.config.renderer.js
[0]
[1]
[1] > wexond@6.0.0-nightly.2 dev-webpack
[1] > cross-env DEV=1 webpack
[1]
[0] i ｢wds｣: Project is running at http://localhost:4444/
[0] i ｢wds｣: webpack output is served from /
[0] i ｢wds｣: Content not from webpack is served from C:\Users\jarno\Desktop\browser-base-master\browser-base-master\build
[1] asset main.bundle.js 8.71 MiB [emitted] (name: main)
[1] asset preload.js 4.16 KiB [emitted] [from: node_modules/@cliqz/adblocker-electron-preload/dist/preload.cjs.js] [copied]
[1] runtime modules 1.04 KiB 5 modules
[1] modules by path ./node_modules/ 3.16 MiB
[1]   javascript modules 2.88 MiB 480 modules
[1]   json modules 284 KiB 5 modules
[1] modules by path ./src/ 145 KiB
[1]   modules by path ./src/main/ 118 KiB 35 modules
[1]   modules by path ./src/utils/*.ts 15.1 KiB 10 modules
[1]   modules by path ./src/constants/*.ts 11.4 KiB 6 modules
[1]   modules by path ./src/common/ 828 bytes 3 modules
[1] modules by path external "require(/ 168 bytes
[1]   external "require(\"electron\")" 42 bytes [built] [code generated]
[1]   external "require(\"os\")" 42 bytes [built] [code generated]
[1]   external "require(\"path\")" 42 bytes [built] [code generated]
[1]   external "require(\"fs\")" 42 bytes [built] [code generated]
[1] 15 modules
[1] webpack 5.40.0 compiled successfully in 11486 ms
[1]
[1] asset view-preload.bundle.js 36.3 KiB [emitted] (name: view-preload)
[1] asset extensions-preload.bundle.js 6.04 KiB [emitted] (name: extensions-preload)
[1] asset popup-preload.bundle.js 2.32 KiB [emitted] (name: popup-preload)
[1] modules by path ./src/ 31.4 KiB
[1]   modules by path ./src/preloads/ 16.6 KiB 10 modules
[1]   modules by path ./src/utils/*.ts 2.24 KiB
[1]     ./src/utils/themes.ts 373 bytes [built] [code generated]
[1]     ./src/utils/form-fill.ts 1.87 KiB [built] [code generated]
[1]   modules by path ./src/constants/*.ts 8.73 KiB
[1]     ./src/constants/files.ts 786 bytes [built] [code generated]
[1]     ./src/constants/settings.ts 7.96 KiB [built] [code generated]
[1]   modules by path ./src/renderer/constants/*.ts 3.81 KiB
[1]     ./src/renderer/constants/themes.ts 2.78 KiB [built] [code generated]
[1]     ./src/renderer/constants/colors.ts 1.03 KiB [built] [code generated]
[1] external "require(\"electron\")" 42 bytes [built] [code generated]
[1] ./node_modules/electron-extensions/preload.js 31 bytes [built] [code generated]
[1] ./build/preload.js 3.68 KiB [built] [code generated]
[1] webpack 5.40.0 compiled successfully in 6045 ms
[0] i ｢wdm｣: wait until bundle finished: /
[1] assets by status 8.71 MiB [cached] 1 asset
[1] asset preload.js 4.16 KiB [emitted] [from: node_modules/@cliqz/adblocker-electron-preload/dist/preload.cjs.js] [copied]
[1] cached modules 3.3 MiB (javascript) 1.04 KiB (runtime) [cached] 618 modules
[1] webpack 5.40.0 compiled successfully in 844 ms
[1]
[1] assets by status 45.1 KiB [cached] 3 assets
[1] cached modules 31.5 KiB [cached] 18 modules
[1] ./build/preload.js 4.16 KiB [built]
[1] webpack 5.40.0 compiled successfully in 32 ms
[1] assets by status 45.1 KiB [cached] 3 assets
[1] cached modules 31.5 KiB [cached] 18 modules
[1] ./build/preload.js 4.16 KiB [built]
[1] webpack 5.40.0 compiled successfully in 101 ms
[1] 
[1] > wexond@6.0.0-nightly.2 start
[1] > electron .
[1]
[1] 
[0] i ｢wdm｣: assets by path res/ 257 KiB
[0]   assets by path res/*.svg 21.3 KiB 54 assets
[0]   assets by path res/*.png 90.2 KiB 12 assets
[0]   assets by path res/*.woff2 145 KiB
[0]     asset res/c90d94fb3f94e426c31e82cafadc524c.woff2 49 KiB [emitted] [immutable] [from: src/renderer/resources/fonts/roboto-medium.woff2]
[0]     asset res/7d1febe76014e661e3f2a3827be43d5e.woff2 48.2 KiB [emitted] [immutable] [from: src/renderer/resources/fonts/roboto-light.woff2]
[0]     asset res/e9a9d280f48fac104245f45ce1a44e33.woff2 48.1 KiB [emitted] [immutable] [from: src/renderer/resources/fonts/roboto-regular.woff2]
[0] assets by path *.js 7 MiB
[0]   assets by chunk 4.62 MiB (id hint: vendors)
[0]     asset vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ErrorOverlayEntry_js-node_mod-d203bb.bundle.js 4.43 MiB [emitted] (id hint: vendors)
[0]     asset vendors-node_modules_animejs_lib_anime_es_js-node_modules_react-windows-controls_build_index_js.bundle.js 127 KiB [emitted] (id hint: vendors)
[0]     asset vendors-node_modules_electron_remote_renderer_index_js.bundle.js 70.1 KiB [emitted] (id hint: vendors)
[0]   27 assets
[0] assets by path *.html 15.3 KiB 15 assets
[0] runtime modules 30.1 KiB 15 modules
[0] modules by path ./src/ 954 KiB
[0]   modules by path ./src/renderer/ 871 KiB 251 modules
[0]   modules by path ./src/utils/*.ts 29.9 KiB 9 modules
[0]   modules by path ./src/constants/*.ts 24 KiB 5 modules
[0]   modules by path ./src/common/ 11.6 KiB 4 modules
[0]   modules by path ./src/models/*.ts 9.42 KiB 2 modules
[0]   modules by path ./src/preloads/ 7.3 KiB 2 modules
[0] modules by path ./node_modules/ 1.72 MiB 121 modules
[0] modules by path external "require(/ 168 bytes
[0]   external "require(\"electron\")" 42 bytes [built] [code generated]
[0]   external "require(\"os\")" 42 bytes [built] [code generated]
[0]   external "require(\"path\")" 42 bytes [built] [code generated]
[0]   external "require(\"fs\")" 42 bytes [built] [code generated]
[0] webpack 5.40.0 compiled successfully in 21888 ms
[0]
[0] asset extension-popup.bundle.js 969 KiB [emitted] (name: extension-popup)
[0] asset extension-popup.html 968 bytes [emitted]
[0] runtime modules 25.9 KiB 10 modules
[0] cacheable modules 342 KiB
[0]   modules by path ./node_modules/webpack-dev-server/ 21.2 KiB
[0]     modules by path ./node_modules/webpack-dev-server/client/ 20.9 KiB 10 modules
[0]     modules by path ./node_modules/webpack-dev-server/node_modules/ 296 bytes 2 modules
[0]   modules by path ./node_modules/html-entities/lib/*.js 61 KiB 5 modules
[0]   modules by path ./node_modules/webpack/hot/*.js 4.3 KiB 4 modules
[0]   modules by path ./node_modules/querystring/*.js 4.51 KiB 3 modules
[0]   modules by path ./node_modules/url/*.js 23.1 KiB
[0]     ./node_modules/url/url.js 22.8 KiB [built] [code generated]
[0]     ./node_modules/url/util.js 314 bytes [built] [code generated]
[0] modules by path external "require(/ 84 bytes
[0]   external "require(\"electron\")" 42 bytes [built] [code generated]
[0]   external "require(\"path\")" 42 bytes [built] [code generated]
[0] ./node_modules/webpack/hot/ sync nonrecursive ^\.\/log$ 170 bytes [built] [code generated]
[0] webpack 5.40.0 compiled successfully in 7567 ms
[0] i ｢wdm｣: Compiled successfully.
[1] App threw an error during load
[1] Error: @electron/remote >= 2.x is required for Electron >= 14. See https://github.com/electron/remote/blob/main/docs/migration-2.md for migration instructions.
[1]     at Object.initialize (C:\Users\jarno\Desktop\browser-base-master\browser-base-master\build\main.bundle.js:11059:15)
[1]     at Object../src/main/index.ts (C:\Users\jarno\Desktop\browser-base-master\browser-base-master\build\main.bundle.js:15392:99)
[1]     at __webpack_require__ (C:\Users\jarno\Desktop\browser-base-master\browser-base-master\build\main.bundle.js:102380:42)
[1]     at C:\Users\jarno\Desktop\browser-base-master\browser-base-master\build\main.bundle.js:102444:37
[1]     at Object.<anonymous> (C:\Users\jarno\Desktop\browser-base-master\browser-base-master\build\main.bundle.js:102446:12)
[1]     at Module._compile (node:internal/modules/cjs/loader:1110:14)
[1]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
[1]     at Module.load (node:internal/modules/cjs/loader:982:32)
[1]     at Module._load (node:internal/modules/cjs/loader:823:12)
[1]     at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
